# Generated by Django 5.0.6 on 2024-05-31 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientcompany',
            options={'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='docstype',
            options={'verbose_name_plural': 'Типы документов'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='productparams',
            options={'verbose_name_plural': 'Товары/услуги'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name_plural': 'Типы товаров/услуг'},
        ),
        migrations.AlterField(
            model_name='client',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clientcompany', verbose_name='Компания клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Компания клиента'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.docstype', verbose_name='Тип файла'),
        ),
    ]
