# Generated by Django 5.0.6 on 2024-05-31 11:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_options_alter_clientcompany_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstrip',
            name='depart_date',
            field=models.DateField(default=datetime.date(2024, 5, 31), verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='duration',
            field=models.IntegerField(default=7, verbose_name='Длительность в днях'),
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.worker', verbose_name='Сотрудник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.businesstripreason', verbose_name='Причина поездки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docs',
            name='file',
            field=models.FileField(upload_to='media/static/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 5, 31), verbose_name='День рождения'),
        ),
    ]
