# Generated by Django 5.0.6 on 2024-05-31 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_businesstrip_depart_date_businesstrip_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 31, 11, 42, 19, 41288, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 5, 31, 11, 42, 19, 40145, tzinfo=datetime.timezone.utc), verbose_name='День рождения'),
        ),
    ]
