# Generated by Django 5.0.6 on 2024-06-03 09:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_businesstrip_depart_date_alter_worker_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTripCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True, verbose_name='Город')),
                ('daily_allowance', models.FloatField(default=2000, verbose_name='Суточные')),
            ],
            options={
                'verbose_name_plural': 'Город для отправки в командировку',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Продукты в заказе'},
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 3, 9, 0, 32, 756197, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='additional_phone_number',
            field=models.CharField(max_length=20, verbose_name='Дополнительный номер телефона'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.worker', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productparams', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='productparams',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='additional_phone_number',
            field=models.CharField(max_length=20, verbose_name='Дополнительный номер телефона'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 6, 3, 9, 0, 32, 754944, tzinfo=datetime.timezone.utc), verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.businesstripcity', verbose_name='Город'),
        ),
    ]
