# Generated by Django 5.0.6 on 2024-06-03 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_businesstripcity_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 3, 12, 45, 17, 683822, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='businesstripcity',
            name='city',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 6, 3, 12, 45, 17, 682573, tzinfo=datetime.timezone.utc), verbose_name='День рождения'),
        ),
        migrations.AlterUniqueTogether(
            name='businesstripcity',
            unique_together={('city', 'daily_allowance')},
        ),
    ]
