# Generated by Django 5.0.6 on 2024-06-06 13:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_businesstrip_depart_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 6, 13, 39, 43, 463094, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='additional_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительный номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.docs', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='additional_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительный номер телефона'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 6, 6, 13, 39, 43, 450945, tzinfo=datetime.timezone.utc), verbose_name='День рождения'),
        ),
    ]
