# Generated by Django 5.0.6 on 2024-06-06 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_businesstrip_depart_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='docs',
        ),
        migrations.AlterField(
            model_name='businesstrip',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 6, 16, 55, 39, 217433, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 6, 6, 16, 55, 39, 205315, tzinfo=datetime.timezone.utc), verbose_name='День рождения'),
        ),
        migrations.DeleteModel(
            name='DocsType',
        ),
        migrations.DeleteModel(
            name='Docs',
        ),
    ]
